// js/bible-map.js
export const BIBLE_ABBREVIATIONS = {
    "Gên": "Génesis", "Gén": "Génesis", "Gênesis": "Génesis",
    "Êx": "Êxodo",
    "Êxo": "Êxodo",
    "Lev": "Levítico",
    "Núm": "Números",
    "De": "Deuteronómio", "Deuteronômio": "Deuteronómio",
    "Deut": "Deuteronómio", "Deuteronômio": "Deuteronómio",
    "Jos": "Josué",
    "Jz": "Juízes",
    "Ru": "Rute",
    "1 Sam": "1 Samuel",
    "2 Sam": "2 Samuel",
    "1 Rs": "1 Reis",
    "2 Rs": "2 Reis",
    "1 Crô": "1 Crónicas", "1 Cró": "1 Crónicas",
    "2 Crô": "2 Crónicas", "2 Cró": "2 Crónicas",
    "Esd": "Esdras",
    "Nee": "Neemias",
    "Est": "Ester",
    "Jó": "Jó",
    "Sal": "Salmos", "Salmo": "Salmos",
    "Pro": "Provérbios",
    "Ecl": "Eclesiastes",
    "Cân": "Cântico de Salomão",
    "Isa": "Isaías",
    "Jer": "Jeremias",
    "La": "Lamentações",
    "Ez": "Ezequiel", "Eze": "Ezequiel",
    "Da": "Daniel",
    "Dan": "Daniel",
    "Os": "Oséias",
    "Jl": "Joel",
    "Am": "Amós",
    "Obd": "Obadias",
    "Jon": "Jonas",
    "Miq": "Miqueias",
    "Na": "Naum",
    "Hab": "Habacuque",
    "Sof": "Sofonias",
    "Ag": "Ageu",
    "Za": "Zacarias",
    "Mal": "Malaquias",
    "Mat": "Mateus",
    "Mr": "Marcos",
    "Mar": "Marcos",
    "Luc": "Lucas",
    "Jo": "João",
    "At": "Atos",
    "Rom": "Romanos",
    "1 Cor": "1 Coríntios",
    "2 Cor": "2 Coríntios",
    "Gál": "Gálatas",
    "Efé": "Efésios",
    "Fil": "Filipenses",
    "Col": "Colossenses",
    "1 Te": "1 Tessalonicenses", "1 Tes": "1 Tessalonicenses",
    "2 Te": "2 Tessalonicenses", "2 Tes": "2 Tessalonicenses",
    "1 Tim": "1 Timóteo",
    "2 Tim": "2 Timóteo",
    "Tit": "Tito",
    "Flm": "Filémon", "Filêmon": "Filémon",
    "Heb": "Hebreus",
    "Tia": "Tiago",
    "1 Ped": "1 Pedro",
    "2 Ped": "2 Pedro",
    "1 Jo": "1 João",
    "2 Jo": "2 João",
    "3 Jo": "3 João",
    "Ju": "Judas",
   "re": "Apocalipse",
    "Re": "Apocalipse",
    "apo": "Apocalipse",
    "Apo": "Apocalipse",
    "Revelação": "Apocalipse",
    "Revelacao": "Apocalipse",
    "Apocalipse": "Apocalipse"
};