// js/siglas-data.js

export const SIGLAS_PUBLICACOES = {
    // Livros
    "cl": "Achegue-se a Jeová",
    "rr": "Adoração Pura",
    "wt": "Adore a Deus",
    "ad": "Ajuda",
    "kj": "“As Nações Terão de Saber”",
    "lp": "A Vida Tem Objetivo",
    "be": "Beneficie-se",
    "bh": "Bíblia Ensina",
    "gh": "Boas Novas",
    "sh": "Busca de Deus",
    "sjj": "Cante de Coração",
    "sn": "Cantemos a Jeová",
    "snnw": "Cantemos a Jeová — Novos Cânticos",
    "ssb": "Cantemos Louvores",
    "re": "Clímax de Revelação",
    "kl": "Conhecimento",
    "lvs": "Continue",
    "wcg": "Seja Corajoso",
    "ce": "Criação",
    "ct": "Criador",
    "jd": "Dia de Jeová",
    "ts": "É Esta Vida?",
    "bhs": "Entenda a Bíblia",
    "hs": "Espírito Santo",
    "fy": "Família Feliz",
    "hp": "Felicidade",
    "go": "Governo Mundial",
    "te": "Grande Instrutor",
    "my": "Histórias Bíblicas",
    "lfb": "Histórias da Bíblia",
    "ia": "Imite",
    "lr": "Instrutor",
    "jr": "Jeremias",
    "jy": "Jesus — o Caminho",
    "yy": "Juventude",
    "lv": "‘Mantenha-se’",
    "sg": "Manual da Escola",
    "bw": "Melhor Modo de Vida",
    "gt": "O Maior Homem",
    "ka": "O Reino de Deus de Mil Anos",
    "kr": "O Reino de Deus já Governa!",
    "od": "Organizados",
    "yp": "Os Jovens Perguntam",
    "yp1": "Os Jovens Perguntam 1",
    "yp2": "Os Jovens Perguntam 2",
    "gm": "Palavra de Deus",
    "pm": "Paraíso Restabelecido",
    "tp73": "Paz e Segurança (1973)",
    "scl": "Princípios Bíblicos para a Vida Cristã",
    "jv": "Proclamadores",
    "dp": "Profecia de Daniel",
    "ip-1": "Profecia de Isaías I",
    "ip-2": "Profecia de Isaías II",
    "po": "“Propósito Eterno”",
    "rs": "Raciocínios",
    "sl": "Salvação do Homem",
    "ws": "Segurança Mundial",
    "lff": "Seja Feliz para Sempre!",
    "su": "Sobrevivência",
    "bt": "Testemunho Cabal",
    "si": "“Toda a Escritura”",
    "uw": "Unidos",
    "kc": "“Venha o Teu Reino”",
    "cf": "‘Venha Ser Meu Seguidor’",
    "tp": "Verdadeira Paz",
    "fl": "Vida Familiar",
    "pe": "Viver Para Sempre",

    // Revistas e Brochuras
    "w": "A Sentinela",
    "wp": "A Sentinela (Público)",
    "g": "Despertai!",
    "it-1": "Perspicaz vol. 1",
    "it-2": "Perspicaz vol. 2",
    "it-3": "Perspicaz vol. 3",
    "dx": "Índice das Publicações",
    "km": "Ministério do Reino",
    "mwb": "Manual de Atividades",
    "ypq": "10 Perguntas",
    "lmd": "Ame as Pessoas",
    "gf": "Amigo de Deus",
    "wfg": "Sabedoria de Jesus",
    "lc": "A Vida — Teve um Criador?",
    "fg": "Boas Notícias de Deus",
    "gl": "‘Boa Terra’",
    "brfi": "Triângulos Roxos",
    "ph": "Caminho",
    "ol": "Caminho para a Vida",
    "hb": "Como Pode o Sangue?",
    "rq": "Deus Requer",
    "ed": "Educação",
    "lmn": "“Eis”",
    "yc": "Ensine Seus Filhos",
    "sj": "Escola",
    "ld": "Escute a Deus",
    "ll": "Escute e Viva",
    "sp": "Espíritos dos Mortos",
    "us": "Espíritos Invisíveis",
    "gc": "Existe um Deus Que se Importa?",
    "hf": "Família",
    "je": "Fazer a Vontade de Deus",
    "hu": "Fracasso dos Planos Humanos",
    "fu": "Futuro Seguro",
    "bp": "Governo",
    "ml": "Muito Mais Envolvido na Vida!",
    "dg": "Importa-se Deus?",
    "kp": "Mantenha-se Vigilante!",
    "th": "Melhore seu Ensino",
    "bm": "Mensagem da Bíblia",
    "mb": "Minhas Lições da Bíblia",
    "wi": "Mundo sem Guerra",
    "na": "Nome Divino",
    "pr": "Objetivo da Vida",
    "lf": "Origem da Vida",
    "wj": "Por Que Adorar a Deus",
    "we": "Quando Morre Alguém",
    "ie": "Quando Morremos",
    "bq": "Questão do Sangue",
    "dn": "Regência Divina",
    "sv": "Salvação da Raça Humana",
    "lffi": "Seja Feliz para Sempre! (Brochura)",
    "og": "Soberania de Deus",
    "jt": "Testemunhas de Jeová — Quem São?",
    "br78": "Testemunhas de Jeová no Século 20",
    "nc": "Todas as Nações",
    "td": "Tópicos Bíblicos para Palestrar",
    "ti": "Trindade",
    "ba": "Um Livro para Todas as Pessoas",
    "rk": "Verdadeira Fé",
    "pc": "Verdadeira Paz e Felicidade",
    "hl": "Vida Feliz",
    "la": "Vida Satisfatória",
    "dy": "Vitória Divina",
    "le": "Viva Para Sempre",
    "rj": "Volte para Jeová",
    "jl": "Vontade de Jeová",

    // Multimédia
     "jwbvod": "Vídeo",
     "mwbv": "Vídeo",
     "jwb": "Vídeo"


};